"""empty message

Revision ID: fe53c8588576
Revises: a099ce23f3d4
Create Date: 2018-09-17 13:44:23.657813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe53c8588576'
down_revision = 'a099ce23f3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_association',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
    )
    op.drop_table('postcat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcat',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='postcat_category_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='postcat_post_id_fkey')
    )
    op.drop_table('category_association')
    # ### end Alembic commands ###
